.PHONY:run
run:
	npm run dev


.PHONY:install
install:
	npm install


.PHONY:local_ci
local_ci: test lint


.PHONY:test
test:
	npm test


.PHONY:lint
lint:
	npm run lint
	npm run format


.PHONY:format
format:
	npm run format
