[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.204"
serde_with = "3.8.3"
thiserror = "1.0.61"

[dev-dependencies]
rstest = "0.21.0"
