name: Continuous integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check rust code
        run: cargo fmt --all --check

      - name: Build backend
        run: cargo build

      - name: Run rust tests
        run: cargo test
