name: Continuous integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    services:
      postgres:
        image: postgres:14
        env:
          # Credentials required by postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Lint rust code
        run: make lint

      - name: Run rust tests
        run: |
          cargo install diesel_cli --no-default-features --features postgres
          export DATABASE_URL=postgres://postgres:postgres@127.0.0.1/postgres
          diesel migration run
          cargo test


  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'

    - name: Install frontend dependencies
      run: make install

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Run Playwright tests
      run: make playwright

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
